name: 'dbt_demo'
version: '1.0.0'
config-version: 2

profile: 'dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: ../../dbt_logs
target-path: "../../dbt_target"  
clean-targets:         
  - "../../target"

models:
  dbt:
    dw:
      +materialized: table
